version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: taskflow-backend
    ports:
      - "8800:8800"
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: taskflow-client
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: unless-stopped
